### ISSUE TITLE
just doesnt even work

### ISSUE THREAD

**Issue by ritzable** [Diregamer1/HTML_B-Sides_WEEKS_5-6-INCLUDED#2]
when you play it its stuck on the loading screen (haxe)

**Comment by Diregamer1** [comment]
I know, I can't really do anything about it and I abandoned the project many months before your issue was files. I saw you forked it, if you can make it work, good on you man.

**Comment by ritzable** [comment]
> I know, I can't really do anything about it and I abandoned the project many months before your issue was files. I saw you forked it, if you can make it work, good on you man.

ok, ill try :)
